<?php

return [
    "Cellar",
    "Chapel",
    "Moat",
    "Chancellor",
    "Harbinger",
    "Merchant",
    "Vassal",
    "Village",
    "Woodcutter",
    "Workshop",
    "Bureaucrat",
    "Feast",
    "Gardens",
    "Militia",
    "Moneylender",
    "Poacher",
    "Remodel",
    "Smithy",
    "Spy",
    "Thief",
    "Throne Room",
    "Bandit",
    "Council Room",
    "Festival",
    "Laboratory",
    "Library",
    "Market",
    "Mine",
    "Sentry",
    "Witch",
    "Adventurer",
    "Artisan",
    "Copper",
    "Silver",
    "Gold",
    "Estate",
    "Duchy",
    "Province",
    "Curse",
    "Courtyard",
    "Lurker",
    "Pawn",
    "Secret Chamber",
    "Great Hall",
    "Masquerade",
    "Shanty Town",
    "Steward",
    "Swindler",
    "Wishing Well",
    "Baron",
    "Bridge",
    "Conspirator",
    "Coppersmith",
    "Diplomat",
    "Ironworks",
    "Mill",
    "Mining Village",
    "Scout",
    "Secret Passage",
    "Courtier",
    "Duke",
    "Minion",
    "Patrol",
    "Replace",
    "Saboteur",
    "Torturer",
    "Trading Post",
    "Tribute",
    "Upgrade",
    "Harem",
    "Nobles",
    "Embargo",
    "Haven",
    "Lighthouse",
    "Native Village",
    "Pearl Diver",
    "Ambassador",
    "Astrolabe",
    "Fishing Village",
    "Lookout",
    "Monkey",
    "Sea Chart",
    "Smugglers",
    "Warehouse",
    "Blockade",
    "Caravan",
    "Cutpurse",
    "Island",
    "Navigator",
    "Pirate Ship",
    "Sailor",
    "Salvager",
    "Sea Hag",
    "Tide Pools",
    "Treasure Map",
    "Bazaar",
    "Corsair",
    "Explorer",
    "Ghost Ship",
    "Merchant Ship",
    "Outpost",
    "Pirate",
    "Sea Witch",
    "Tactician",
    "Treasury",
    "Wharf",
    "Transmute",
    "Vineyard",
    "Herbalist",
    "Apothecary",
    "Scrying Pool",
    "University",
    "Alchemist",
    "Familiar",
    "Philosopher's Stone",
    "Golem",
    "Apprentice",
    "Possession",
    "Potion",
    "Anvil",
    "Loan",
    "Trade Route",
    "Watchtower",
    "Bishop",
    "Clerk",
    "Investment",
    "Monument",
    "Quarry",
    "Talisman",
    "Tiara",
    "Worker's Village",
    "Charlatan",
    "City",
    "Collection",
    "Contraband",
    "Counting House",
    "Crystal Ball",
    "Magnate",
    "Mint",
    "Mountebank",
    "Rabble",
    "Royal Seal",
    "Vault",
    "Venture",
    "War Chest",
    "Goons",
    "Grand Market",
    "Hoard",
    "Bank",
    "Expand",
    "Forge",
    "King's Court",
    "Peddler",
    "Platinum",
    "Colony",
    "Hamlet",
    "Fortune Teller",
    "Menagerie",
    "Farming Village",
    "Horse Traders",
    "Remake",
    "Tournament",
    "Young Witch",
    "Harvest",
    "Horn of Plenty",
    "Hunting Party",
    "Jester",
    "Fairgrounds",
    "Bag of Gold",
    "Diadem",
    "Followers",
    "Princess",
    "Trusty Steed",
    "Crossroads",
    "Duchess",
    "Fool's Gold",
    "Develop",
    "Guard Dog",
    "Oasis",
    "Oracle",
    "Scheme",
    "Tunnel",
    "Jack of All Trades",
    "Noble Brigand",
    "Nomad Camp",
    "Nomads",
    "Silk Road",
    "Spice Merchant",
    "Trader",
    "Trail",
    "Weaver",
    "Berserker",
    "Cache",
    "Cartographer",
    "Cauldron",
    "Embassy",
    "Haggler",
    "Highway",
    "Ill-Gotten Gains",
    "Inn",
    "Mandarin",
    "Margrave",
    "Souk",
    "Stables",
    "Wheelwright",
    "Witch's Hut",
    "Border Village",
    "Farmland",
    "Poor House",
    "Beggar",
    "Squire",
    "Vagrant",
    "Forager",
    "Hermit",
    "Market Square",
    "Sage",
    "Storeroom",
    "Urchin",
    "Armory",
    "Death Cart",
    "Feodum",
    "Fortress",
    "Ironmonger",
    "Marauder",
    "Procession",
    "Rats",
    "Scavenger",
    "Wandering Minstrel",
    "Band of Misfits",
    "Bandit Camp",
    "Catacombs",
    "Count",
    "Counterfeit",
    "Cultist",
    "Graverobber",
    "Junk Dealer",
    "Mystic",
    "Pillage",
    "Rebuild",
    "Rogue",
    "Altar",
    "Hunting Grounds",
    "Abandoned Mine",
    "Ruined Library",
    "Ruined Market",
    "Ruined Village",
    "Survivors",
    "Dame Anna",
    "Dame Josephine",
    "Dame Molly",
    "Dame Natalie",
    "Dame Sylvia",
    "Sir Bailey",
    "Sir Destry",
    "Sir Martin",
    "Sir Michael",
    "Sir Vander",
    "Madman",
    "Mercenary",
    "Spoils",
    "Hovel",
    "Necropolis",
    "Overgrown Estate",
    "Candlestick Maker",
    "Stonemason",
    "Doctor",
    "Masterpiece",
    "Advisor",
    "Herald",
    "Plaza",
    "Taxman",
    "Baker",
    "Butcher",
    "Journeyman",
    "Merchant Guild",
    "Soothsayer",
    "Coin of the Realm",
    "Page",
    "Peasant",
    "Ratcatcher",
    "Raze",
    "Amulet",
    "Caravan Guard",
    "Dungeon",
    "Gear",
    "Guide",
    "Duplicate",
    "Magpie",
    "Messenger",
    "Miser",
    "Port",
    "Ranger",
    "Transmogrify",
    "Artificer",
    "Bridge Troll",
    "Distant Lands",
    "Giant",
    "Haunted Woods",
    "Lost City",
    "Relic",
    "Royal Carriage",
    "Storyteller",
    "Swamp Hag",
    "Treasure Trove",
    "Wine Merchant",
    "Hireling",
    "Alms",
    "Borrow",
    "Quest",
    "Save",
    "Scouting Party",
    "Travelling Fair",
    "Bonfire",
    "Expedition",
    "Ferry",
    "Plan",
    "Mission",
    "Pilgrimage",
    "Ball",
    "Raid",
    "Seaway",
    "Trade",
    "Lost Arts",
    "Training",
    "Inheritance",
    "Pathfinding",
    "Soldier",
    "Fugitive",
    "Disciple",
    "Teacher",
    "Treasure Hunter",
    "Warrior",
    "Hero",
    "Champion",
    "Engineer",
    "City Quarter",
    "Royal Blacksmith",
    "Overlord",
    "Encampment",
    "Patrician",
    "Settlers",
    "Catapult",
    "Chariot Race",
    "Enchantress",
    "Farmers' Market",
    "Gladiator",
    "Rocks",
    "Sacrifice",
    "Temple",
    "Villa",
    "Archive",
    "Bustling Village",
    "Capital",
    "Charm",
    "Crown",
    "Emporium",
    "Forum",
    "Groundskeeper",
    "Legionary",
    "Plunder",
    "Wild Hunt",
    "Fortune",
    "Humble Castle",
    "Crumbling Castle",
    "Small Castle",
    "Haunted Castle",
    "Opulent Castle",
    "Sprawling Castle",
    "Grand Castle",
    "King's Castle",
    "Triumph",
    "Annex",
    "Donate",
    "Advance",
    "Delve",
    "Tax",
    "Banquet",
    "Ritual",
    "Salt the Earth",
    "Wedding",
    "Windfall",
    "Conquest",
    "Dominate",
    "Aqueduct",
    "Arena",
    "Bandit Fort",
    "Basilica",
    "Battlefield",
    "Baths",
    "Colonnade",
    "Defiled Shrine",
    "Fountain",
    "Keep",
    "Labyrinth",
    "Mountain Pass",
    "Museum",
    "Obelisk",
    "Orchard",
    "Palace",
    "Tomb",
    "Tower",
    "Triumphal Arch",
    "Wall",
    "Wolf Den",
    "Druid",
    "Faithful Hound",
    "Guardian",
    "Monastery",
    "Pixie",
    "Tracker",
    "Changeling",
    "Fool",
    "Ghost Town",
    "Leprechaun",
    "Night Watchman",
    "Secret Cave",
    "Bard",
    "Blessed Village",
    "Cemetery",
    "Conclave",
    "Devil's Workshop",
    "Exorcist",
    "Necromancer",
    "Shepherd",
    "Skulk",
    "Cobbler",
    "Crypt",
    "Cursed Village",
    "Den of Sin",
    "Idol",
    "Pooka",
    "Sacred Grove",
    "Tormentor",
    "Tragic Hero",
    "Vampire",
    "Werewolf",
    "Raider",
    "Will-o'-Wisp",
    "Wish",
    "Bat",
    "Imp",
    "Ghost",
    "Zombie Apprentice",
    "Zombie Mason",
    "Zombie Spy",
    "Haunted Mirror",
    "Magic Lamp",
    "Goat",
    "Pasture",
    "Pouch",
    "Cursed Gold",
    "Lucky Coin",
    "The Earth's Gift",
    "The Field's Gift",
    "The Flame's Gift",
    "The Forest's Gift",
    "The Moon's Gift",
    "The Mountain's Gift",
    "The River's Gift",
    "The Sea's Gift",
    "The Sky's Gift",
    "The Sun's Gift",
    "The Swamp's Gift",
    "The Wind's Gift",
    "Bad Omens",
    "Delusion",
    "Envy",
    "Famine",
    "Fear",
    "Greed",
    "Haunting",
    "Locusts",
    "Misery",
    "Plague",
    "Poverty",
    "War",
    "Deluded",
    "Envious",
    "Lost in the Woods",
    "Miserable",
    "Twice Miserable",
    "Border Guard",
    "Ducat",
    "Lackeys",
    "Acting Troupe",
    "Cargo Ship",
    "Experiment",
    "Improve",
    "Flag Bearer",
    "Hideout",
    "Inventor",
    "Mountain Village",
    "Patron",
    "Priest",
    "Research",
    "Silk Merchant",
    "Old Witch",
    "Recruiter",
    "Scepter",
    "Scholar",
    "Sculptor",
    "Seer",
    "Spices",
    "Swashbuckler",
    "Treasurer",
    "Villain",
    "Flag",
    "Horn",
    "Key",
    "Lantern",
    "Treasure Chest",
    "Cathedral",
    "City Gate",
    "Pageant",
    "Sewers",
    "Star Chart",
    "Exploration",
    "Fair",
    "Silos",
    "Sinister Plot",
    "Academy",
    "Capitalism",
    "Fleet",
    "Guildhall",
    "Piazza",
    "Road Network",
    "Barracks",
    "Crop Rotation",
    "Innovation",
    "Canal",
    "Citadel",
    "Black Cat",
    "Sleigh",
    "Supplies",
    "Horse",
    "Camel Train",
    "Goatherd",
    "Scrap",
    "Sheepdog",
    "Snowy Village",
    "Stockpile",
    "Bounty Hunter",
    "Cardinal",
    "Cavalry",
    "Groom",
    "Hostelry",
    "Village Green",
    "Fisherman",
    "Hunting Lodge",
    "Barge",
    "Coven",
    "Displace",
    "Falconer",
    "Gatekeeper",
    "Kiln",
    "Livery",
    "Mastermind",
    "Paddock",
    "Sanctuary",
    "Destrier",
    "Wayfarer",
    "Animal Fair",
    "Delay",
    "Desperation",
    "Gamble",
    "Pursue",
    "Ride",
    "Toil",
    "Enhance",
    "March",
    "Transport",
    "Banish",
    "Bargain",
    "Invest",
    "Seize the Day",
    "Commerce",
    "Demand",
    "Stampede",
    "Reap",
    "Enclave",
    "Alliance",
    "Populate",
    "Way of the Butterfly",
    "Way of the Camel",
    "Way of the Chameleon",
    "Way of the Frog",
    "Way of the Goat",
    "Way of the Horse",
    "Way of the Mole",
    "Way of the Monkey",
    "Way of the Mouse",
    "Way of the Mule",
    "Way of the Otter",
    "Way of the Ox",
    "Way of the Owl",
    "Way of the Pig",
    "Way of the Rat",
    "Way of the Seal",
    "Way of the Sheep",
    "Way of the Squirrel",
    "Way of the Turtle",
    "Way of the Worm",
    "Bauble",
    "Sycophant",
    "Merchant Camp",
    "Importer",
    "Sentinel",
    "Underling",
    "Broker",
    "Carpenter",
    "Courier",
    "Innkeeper",
    "Royal Galley",
    "Town",
    "Barbarian",
    "Capital City",
    "Contract",
    "Emissary",
    "Galleria",
    "Guildmaster",
    "Highwayman",
    "Hunter",
    "Modify",
    "Skirmisher",
    "Specialist",
    "Swap",
    "Marquis",
    "Town Crier",
    "Herb Gatherer",
    "Old Map",
    "Blacksmith",
    "Student",
    "Tent",
    "Battle Plan",
    "Acolyte",
    "Voyage",
    "Miller",
    "Conjurer",
    "Garrison",
    "Archer",
    "Sorceress",
    "Sunken Treasure",
    "Elder",
    "Sorcerer",
    "Hill Fort",
    "Warlord",
    "Sibyl",
    "Distant Shore",
    "Lich",
    "Stronghold",
    "Territory",
    "Architects' Guild",
    "Band of Nomads",
    "Cave Dwellers",
    "Circle of Witches",
    "City-state",
    "Coastal Haven",
    "Crafters' Guild",
    "Desert Guides",
    "Family of Inventors",
    "Fellowship of Scribes",
    "Forest Dwellers",
    "Gang of Pickpockets",
    "Island Folk",
    "League of Bankers",
    "League of Shopkeepers",
    "Market Towns",
    "Mountain Folk",
    "Order of Astrologers",
    "Order of Masons",
    "Peaceful Cult",
    "Plateau Shepherds",
    "Trappers' Lodge",
    "Woodworkers' Guild",
    "Black Market",
    "Church",
    "Dismantle",
    "Envoy",
    "Sauna",
    "Walled Village",
    "Avanto",
    "Governor",
    "Stash",
    "Summon",
    "Captain",
    "Prince"
];
