<?php

return [
  "Abandoned Mine",
  "Copper",
  "Curse",
  "Estate",
  "Silver",
  "Duchy",
  "Gold",
  "Province",
  "Cellar",
  "Chapel",
  "Moat",
  "Harbinger",
  "Merchant",
  "Vassal",
  "Village",
  "Workshop",
  "Bureaucrat",
  "Gardens",
  "Militia",
  "Moneylender",
  "Poacher",
  "Remodel",
  "Smithy",
  "Throne Room",
  "Bandit",
  "Council Room",
  "Festival",
  "Laboratory",
  "Library",
  "Market",
  "Mine",
  "Sentry",
  "Witch",
  "Artisan",
  "Chancellor",
  "Woodcutter",
  "Feast",
  "Spy",

  "Thief",
  "Adventurer",
  "Courtyard",
  "Lurker",
  "Pawn",
  "Masquerade",
  "Shanty Town",
  "Steward",
  "Swindler",
  "Wishing Well",
  "Baron",
  "Bridge",
  "Conspirator",
  "Diplomat",
  "Ironworks",
  "Mill",
  "Mining Village",
  "Secret Passage",
  "Courtier",
  "Duke",
  "Minion",
  "Patrol",
  "Replace",
  "Torturer",
  "Trading Post",
  "Upgrade",
  "Harem",
  "Nobles",
  "Secret Chamber",
  "Great Hall",
  "Coppersmith",
  "Scout",
  "Saboteur",
  "Tribute",
  "Embargo",
  "Haven",
  "Lighthouse",
  "Native Village",
  "Pearl Diver",
  "Ambassador",
  "Fishing Village",
  "Lookout",
  "Smugglers",
  "Warehouse",
  "Caravan",
  "Cutpurse",
  "Island",
  "Navigator",
  "Pirate Ship",
  "Salvager",
  "Sea Hag",
  "Treasure Map",
  "Bazaar",
  "Explorer",
  "Ghost Ship",
  "Merchant Ship",
  "Outpost",
  "Tactician",
  "Treasury",
  "Wharf",
  "Transmute",
  "Vineyard",
  "Herbalist",
  "Apothecary",
  "Scrying Pool",

  "University",
  "Alchemist",
  "Familiar",
  "Philosopher's Stone",
  "Potion",
  "Golem",
  "Apprentice",
  "Possession",
  "Loan",
  "Trade Route",
  "Watchtower",
  "Bishop",
  "Monument",
  "Quarry",
  "Talisman",
  "Worker's Village",
  "City",
  "Contraband",
  "Counting House",
  "Mint",
  "Mountebank",
  "Rabble",
  "Royal Seal",
  "Vault",
  "Venture",
  "Goons",
  "Hoard",
  "Grand Market",
  "Bank",
  "Expand",
  "Forge",
  "King's Court",
  "Peddler",
  "Platinum",
  "Colony",
  "Hamlet",
  "Fortune Teller",
  "Menagerie",
  "Farming Village",
  "Horse Traders",
  "Remake",
  "Tournament",
  "Bag of Gold",
  "Diadem",
  "Followers",
  "Princess",
  "Trusty Steed",
  "Young Witch",
  "Harvest",
  "Horn of Plenty",
  "Hunting Party",
  "Jester",
  "Fairgrounds",
  "Crossroads",
  "Duchess",
  "Fool's Gold",
  "Develop",
  "Oasis",
  "Oracle",
  "Scheme",
  "Tunnel",
  "Jack of All Trades",
  "Noble Brigand",
  "Nomad Camp",
  "Silk Road",
  "Spice Merchant",
  "Trader",
  "Cache",
  "Cartographer",
  "Embassy",
  "Haggler",
  "Highway",
  "Ill-Gotten Gains",
  "Inn",
  "Mandarin",

  "Margrave",
  "Stables",
  "Border Village",
  "Farmland",
  "Abandoned Mine",
  "Ruined Library",
  "Ruined Market",
  "Ruined Village",
  "Survivors",
  "Spoils",
  "Poor House",
  "Hovel",
  "Necropolis",
  "Overgrown Estate",
  "Beggar",
  "Squire",
  "Vagrant",
  "Forager",
  "Hermit",
  "Madman",
  "Market Square",
  "Sage",
  "Storeroom",
  "Urchin",
  "Mercenary",
  "Armory",
  "Death Cart",
  "Feodum",
  "Fortress",
  "Ironmonger",
  "Marauder",
  "Procession",
  "Rats",
  "Scavenger",
  "Wandering Minstrel",
  "Band of Misfits",
  "Bandit Camp",
  "Catacombs",
  "Count",
  "Counterfeit",
  "Cultist",
  "Graverobber",
  "Junk Dealer",
  "Knights",
  "Dame Anna",
  "Dame Josephine",
  "Dame Molly",
  "Dame Natalie",
  "Dame Sylvia",
  "Sir Bailey",
  "Sir Destry",
  "Sir Martin",
  "Sir Michael",
  "Sir Vander",
  "Mystic",
  "Pillage",
  "Rebuild",
  "Rogue",
  "Altar",
  "Hunting Grounds",
  "Candlestick Maker",
  "Stonemason",
  "Doctor",
  "Masterpiece",
  "Advisor",
  "Plaza",
  "Taxman",
  "Herald",
  "Baker",
  "Butcher",
  "Journeyman",
  "Merchant Guild",
  "Soothsayer",
  "Coin of the Realm",
  "Page",
  "Treasure Hunter",
  "Warrior",
  "Hero",
  "Champion",
  "Peasant",
  "Soldier",
  "Fugitive",
  "Disciple",
  "Teacher",
  "Ratcatcher",
  "Raze",
  "Amulet",
  "Caravan Guard",
  "Dungeon",
  "Gear",
  "Guide",
  "Duplicate",
  "Magpie",
  "Messenger",
  "Miser",
  "Port",
  "Ranger",
  "Transmogrify",

  "Artificer",
  "Bridge Troll",
  "Distant Lands",
  "Giant",
  "Haunted Woods",
  "Lost City",
  "Relic",
  "Royal Carriage",
  "Storyteller",
  "Swamp Hag",
  "Treasure Trove",
  "Wine Merchant",
  "Hireling",
  "Alms",
  "Borrow",
  "Quest",
  "Save",
  "Scouting Party",
  "Travelling Fair",
  "Bonfire",
  "Expedition",
  "Ferry",
  "Plan",
  "Mission",
  "Pilgrimage",
  "Ball",
  "Raid",
  "Seaway",
  "Trade",
  "Lost Arts",
  "Training",
  "Inheritance",
  "Pathfinding",
  "Engineer",
  "City Quarter",
  "Overlord",
  "Royal Blacksmith",
  "Encampment",
  "Plunder",
  "Patrician",
  "Emporium",
  "Settlers",
  "Bustling Village",
  "Castles",
  "Humble Castle",
  "Crumbling Castle",
  "Small Castle",
  "Haunted Castle",
  "Opulent Castle",
  "Sprawling Castle",
  "Grand Castle",
  "King's Castle",
  "Catapult",
  "Rocks",
  "Chariot Race",
  "Enchantress",
  "Farmers' Market",
  "Gladiator",
  "Fortune",
  "Sacrifice",
  "Temple",
  "Villa",
  "Archive",
  "Capital",
  "Charm",
  "Crown",
  "Forum",
  "Groundskeeper",
  "Legionary",
  "Wild Hunt",
  "Triumph",
  "Annex",
  "Donate",
  "Advance",
  "Delve",
  "Tax",
  "Banquet",
  "Ritual",
  "Salt the Earth",
  "Wedding",
  "Windfall",
  "Conquest",
  "Dominate",
  "Aqueduct",
  "Arena",
  "Bandit Fort",
  "Basilica",
  "Baths",
  "Battlefield",
  "Colonnade",
  "Defiled Shrine",
  "Fountain",
  "Keep",
  "Labyrinth",
  "Mountain Pass",
  "Museum",
  "Obelisk",
  "Orchard",
  "Palace",
  "Tomb",
  "Tower",
  "Triumphal Arch",
  "Wall",
  "Wolf Den",
  "Will-o'-Wisp",
  "Wish",
  "Druid",
  "Faithful Hound",
  "Guardian",
  "Monastery",
  "Pixie",
  "Goat",
  "Tracker",
  "Pouch",
  "Imp",
  "Changeling",
  "Fool",
  "Lost in the Woods",
  "Lucky Coin",
  "Ghost Town",
  "Leprechaun",
  "Night Watchman",
  "Secret Cave",
  "Magic Lamp",
  "Bard",
  "Blessed Village",
  "Cemetery",
  "Haunted Mirror",
  "Conclave",
  "Devil's Workshop",
  "Exorcist",
  "Necromancer",
  "Zombie Apprentice",
  "Zombie Mason",
  "Zombie Spy",
  "Shepherd",
  "Pasture",
  "Skulk",
  "Ghost",
  "Cobbler",
  "Crypt",
  "Cursed Village",
  "Den of Sin",
  "Idol",
  "Pooka",
  "Cursed Gold",
  "Sacred Grove",
  "Tormentor",
  "Tragic Hero",
  "Vampire",
  "Bat",
  "Werewolf",
  "Raider",
  "The Earth's Gift",
  "The Field's Gift",
  "The Flame's Gift",
  "The Forest's Gift",
  "The Moon's Gift",
  "The Mountain's Gift",
  "The River's Gift",
  "The Sea's Gift",
  "The Sky's Gift",
  "The Sun's Gift",
  "The Swamp's Gift",
  "The Wind's Gift",
  "Bad Omens",
  "Delusion",
  "Deluded",
  "Envy",
  "Envious",
  "Famine",
  "Fear",
  "Greed",
  "Haunting",
  "Locusts",
  "Misery",
  "Miserable",
  "Twice Miserable",
  "Plague",
  "Poverty",
  "War",
  "Border Guard",
  "Horn",
  "Lantern",
  "Ducat",
  "Lackeys",
  "Acting Troupe",
  "Cargo Ship",
  "Experiment",
  "Improve",
  "Flag Bearer",
  "Flag",
  "Hideout",
  "Inventor",
  "Mountain Village",
  "Patron",
  "Priest",
  "Research",
  "Silk Merchant",
  "Old Witch",
  "Recruiter",
  "Scepter",
  "Scholar",
  "Sculptor",
  "Seer",
  "Spices",
  "Swashbuckler",
  "Treasure Chest",
  "Treasurer",
  "Key",
  "Villain",
  "Cathedral",
  "City Gate",
  "Pageant",
  "Sewers",
  "Star Chart",
  "Exploration",
  "Fair",
  "Silos",
  "Sinister Plot",
  "Academy",
  "Capitalism",
  "Fleet",
  "Guildhall",
  "Piazza",
  "Road Network",
  "Barracks",
  "Crop Rotation",
  "Innovation",
  "Canal",
  "Citadel",
  "Black Cat",
  "Sleigh",
  "Supplies",
  "Camel Train",
  "Goatherd",
  "Scrap",
  "Sheepdog",
  "Snowy Village",
  "Stockpile",
  "Horse",
  "Bounty Hunter",
  "Cardinal",
  "Cavalry",
  "Groom",
  "Hostelry",
  "Village Green",
  "Barge",
  "Coven",
  "Displace",
  "Falconer",
  "Gatekeeper",
  "Hunting Lodge",
  "Kiln",
  "Livery",
  "Mastermind",
  "Paddock",
  "Sanctuary",
  "Fisherman",
  "Destrier",
  "Wayfarer",
  "Animal Fair",
  "Delay",
  "Desperation",
  "Gamble",
  "Pursue",
  "Ride",
  "Toil",
  "Enhance",
  "March",
  "Transport",
  "Banish",
  "Bargain",
  "Invest",
  "Seize the Day",
  "Commerce",
  "Demand",
  "Stampede",
  "Reap",
  "Enclave",
  "Alliance",
  "Populate",
  // "Way of the Butterfly",
  // "Way of the Camel",
  // "Way of the Chameleon",
  // "Way of the Frog",
  // "Way of the Goat",
  // "Way of the Horse",
  // "Way of the Mole",
  // "Way of the Monkey",
  // "Way of the Mouse",
  // "Way of the Mule",
  // "Way of the Otter",
  // "Way of the Owl",
  // "Way of the Ox",
  // "Way of the Pig",
  // "Way of the Rat",
  // "Way of the Seal",
  // "Way of the Sheep",
  // "Way of the Squirrel",
  // "Way of the Turtle",
  // "Way of the Worm",
  "Black Market",
  "Church",
  "Dismantle",
  "Envoy",
  "Sauna",
  "Avanto",
  "Walled Village",
  "Governor",
  "Stash",
  "Captain",
  "Prince",
  "Summon"
];
